### ISSUE TITLE
Doom guy gets stuck walking in 1 direction

### ISSUE THREAD

**Issue by warlockv2** [fgsfdsfgs/Doom64EX#1] opened 2018-10-20 11:54 UTC
Aftter playing for 5 minutes my guy just keeps walking in a certain direction. Like it gets stuck.  And becomes unplayable.  Restarting game fixes it.  But a few minutes

**Comment by fgsfdsfgs** [comment] 2018-11-23 00:14
I'm unable to reproduce this. Tried wiggling around the stick and just playing the game normally for around 15 minutes, nothing so far. I'll keep trying, but maybe you can pinpoint what exactly causes it to lock up?

**Comment by warlockv2** [comment] 2018-11-23 01:11
I wish i could tell you.  Its random for me.  I can play for 2 levels.  And
its fine.  Or 2 minutes and i have to save and restart cause he just walks
into walls...  i only use a pro controller tho.   So its wireless and docked

**Comment by fgsfdsfgs** [comment] 2018-11-23 01:24
[doom64ex.zip](https://github.com/fgsfdsfgs/Doom64EX/files/2609489/doom64ex.zip)
Try this NRO.

**Comment by warlockv2** [comment] 2018-11-23 01:26
Ok i will.  Il let you know.  Thanks for the help

**Comment by warlockv2** [comment] 2018-11-25 18:58
No luck sadly.  Loaded a save and after about 1 min i was walking against
walls again...

Also now im on sxos as before i used reinx. And  same outcome.   Pro
controller still im testing with joycons now

**Comment by warlockv2** [comment] 2018-11-25 19:00
Same with joycons.

**Comment by cucholix** [comment] 2019-04-13 14:23
I recently formatted my exFAT SD to FAT32, and I used to have the same issue with the left stick, I was able to complete a level (around 15 minutes) and couldn’t trigger the bug, so maybe it was exFAT fault?

**Comment by warlockv2** [comment] 2019-04-13 15:12
Nah i use fat32.  Im unsure why this is happening.  I still play it.
 Cause its an awesome port.  I just have to save and load constantly

**Comment by cucholix** [comment] 2019-04-13 15:22
I formatted to fat32, 32kb cluster. Haven’t done anything else, and like you the issue triggered constantly with exFAT. @fgsfdsfgs mentioned that he wasn’t able to reproduce the bug, it could be interesting narrow the issue with his setup.

**Comment by cucholix** [comment] 2019-04-13 18:13
Update: yeah testing in docked mode with Nintendo brand pro controller and the left stick get stuck within the first 10 seconds :/

There’s definitely an issue with stick dead zones, my stick in left joy con is a little loose compared to my pro, that’s the only difference that I can detect.

**Comment by warlockv2** [comment] 2019-04-14 15:38
Yeah.  I don't know why the creator hasn't had this issue...  nice to see
someone elae with the problem tho so i dont look crazy now hahaha

**Comment by fgsfdsfgs** [comment] 2019-04-14 17:51
I have since reproduced it once on accident, but I still can't figure out what exactly causes it. It definitely has nothing to do with your filesystem.

**Comment by warlockv2** [comment] 2019-04-14 18:39
I don't think so either.  I tried with joycons.  I tried with pro
controller. And i tried with joycons attached.   No good.  In fact i cant
get 2 mins in anymore without it doing it.

Like it progressivly for worse lol

**Comment by fgsfdsfgs** [comment] 2019-10-23 17:08
This has been hopefully fixed in v0.2.0.

**Closed as completed by fgsfdsfgs** 2019-10-23 17:08 UTC

**Comment by warlockv2** [comment] 2019-10-23 17:44
Awesome
